// Generated by https://quicktype.io

export interface WordItem {
  id:           number;
  word_list_id: number;
  word:         string;
  translation:  string;
  created_at:   string;
  updated_at:   string;
}
